// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_API_CORE.Data;

namespace WEB_API_CORE.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200722215549_mudaColunasNome")]
    partial class mudaColunasNome
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WEB_API_CORE.Models.CATEGORIA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("ID");

                    b.ToTable("CATEGORIAS");
                });

            modelBuilder.Entity("WEB_API_CORE.Models.LOTE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DATA")
                        .HasColumnType("datetime2");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("LOTES");
                });

            modelBuilder.Entity("WEB_API_CORE.Models.PRODUTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CATEGORIAID")
                        .HasColumnType("int");

                    b.Property<string>("DESCRICAO")
                        .HasColumnType("nvarchar(1024)")
                        .HasMaxLength(1024);

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<decimal>("PRECO")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ID");

                    b.HasIndex("CATEGORIAID");

                    b.ToTable("PRODUTOS");
                });

            modelBuilder.Entity("WEB_API_CORE.Models.REMESSA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("B1_DESC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B1_EDICAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B1_FILIAL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B1_GRUPO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B1_TAMANHO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B1_YMODELO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DATA_EMISSAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMAGEM_0")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMAGEM_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMAGEM_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LOTEID")
                        .HasColumnType("int");

                    b.Property<string>("ZZJ_CODCLI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZZJ_CODPRO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZZJ_FILIAL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZZJ_ITEMNF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZZJ_LOJA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZZJ_QTDFAT")
                        .HasColumnType("int");

                    b.Property<double>("ZZJ_SALDO")
                        .HasColumnType("float");

                    b.Property<string>("ZZJ_SERIE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LOTEID");

                    b.ToTable("REMESSAS");
                });

            modelBuilder.Entity("WEB_API_CORE.Models.USUARIO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ACESSO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPF_CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("NOME_SOBRENOME")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("SENHA")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("ID");

                    b.ToTable("USUARIOS");
                });

            modelBuilder.Entity("WEB_API_CORE.Models.PRODUTO", b =>
                {
                    b.HasOne("WEB_API_CORE.Models.CATEGORIA", "CATEGORIA")
                        .WithMany()
                        .HasForeignKey("CATEGORIAID");
                });

            modelBuilder.Entity("WEB_API_CORE.Models.REMESSA", b =>
                {
                    b.HasOne("WEB_API_CORE.Models.LOTE", "LOTE")
                        .WithMany("REMESSA")
                        .HasForeignKey("LOTEID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
